### ISSUE TITLE
Domain != Locale

### ISSUE THREAD

**Issue by ArmorDarks** [alexanderwallin/node-gettext#24]
It was quite surprising to me, but seems that `node-gettext` uses domains in the way they weren't supposed to be used. Or, at least, proposes to use them in wrong manner.

In original gettext domains are more like `context`, and usually it's pulled from file's name.

For instance, `messages.po` usually will have default domain `messages`, while `payment.po` will have domain `payment`.

Locale's data should be controlled through other means. For now `node-gettext` uses domains for locales, which makes maintaining of complex projects uneasy task, since you can't store unrelated messages in separate file, and then pull them into one locale with different domains and contexts.

Merging of `.po` files won't help here, since in such cases usually you need to keep domain information.

Though, to be honest, I still don't get is it possible to switch locales on the fly in original gettext or no.

**Comment by alexanderwallin** [comment]
This is being resolve in [v2](https://github.com/alexanderwallin/node-gettext/tree/v2).
