### ISSUE TITLE
Make binding methods closer to GNU gettext

### ISSUE THREAD

**Issue by ArmorDarks** [alexanderwallin/node-gettext#31]
Hi

I just saw that you've released 2.0.0 rc. I've gone through docs of GNU gettexts few days ago, and played for awhile with JS to see how exactly locales and textdomain binding done in GNU gettext, and turned out that it done quite differently from docs of current 2.0.0 rc.

Are you still open for some radical changes? Otherwise, I don't want to waste time on describing something, that won't be took into lib anyway :)

**Comment by alexanderwallin** [comment]
I was just about to post in the thread about the update.

Of course I want to hear your opinion! Shoot. 😊

**Comment by ArmorDarks** [comment]
I know that I had to post this sooner :) Was too lazy...

Ok, I will try to do this when I'll got home, in about few hours.

**Comment by ArmorDarks** [comment]
Ok, I'm here. That will be a long read.

First of all, just to clear this out from the beginning, what I'm going to say further has absolutely nothing to do with translation functions, like `gettext`, `pgettext` and so on. As far as it seems to me, they works according to the specs, or close to it.

However, other functions seems to work differently in GNU gettext, and I think it worth to see how exactly do they differ, to take best from their implementations.

# gettext.setLocale(locale)

GNU has similar to implemented in 2.0.0 `setLocale` method, named `setlocale`.

Differences:

1. Different naming — `setlocale` in GNU and `setLocale` in 2.0.0 

   I think we can leave with the fact, that setLocale named differently, though, maybe it won't be bad idea to unify naming. But in same time I understand, that in JS community it is more common to name methods with complete camelcase, while C++ seems to prefer everything flat. That thing is subjective.

2. Important part. In GNU gettext there is no need to add translations with `addTranslations` nor any other methods.

   Instead, `setlocale` in GNU servers as

     1) Way to switch locale
     2) _If there is currently no such locale, initiate requested locale_

   So, technically GNU gettext doesn't care do you have any translation for specific locale or no, did you initiate it somewhere or not. And after giving it a though, it seemed reasonable for me.

   You see, it might happen so that you want to tell your application, that locale should be switched to "that locale", and it's not important for you, does this locale exist or no. You might add translations for this locale later in your code, but switching should be done right now.

   As for illustration, with pre-2.0.0 `node-gettext` I've achieved same thing by writing my own `setLocale` method, which initiates new locale for every new `setLocale`, or switches to already existing locale, if there is such. You can see code example [here](https://github.com/LotusTM/Kotsu/blob/master/modules/gettext.coffee#L13).

   GNU gettext way is elegant, since it doesn't make any assumptions about your environment, nor forces you to declare something in forehead. You've asked about that locale? You've got it.

   Just as a side note, in C++ such behaviour dictated by the fact, that each locale is already _might_ exist in system (since usually as environment for Gettext serves OS), thus it can't rely on the fact that something will be declared in forehead. If you will switch to certain locale, gettext will just try to get best out of system environment for you, by matching best LC_MESSAGES and other categories. But if there is no translation in system for setted locale, it doesn't mean that application should crash, throw an error, or don't switch locale. Locale has to be switched anyway, despite that for requested strings will be used original, untranslated texts.

3. Just a nuance. In GNU gettext `setlocale` also controls which LC_* category will be set for chosen locale.

    Because of that it has different signature:

    ``` js
    gettext.setLocale(localeName)
    gettext.setlocale(LC_name, localeName) // GNU one
    ```

    While this isn't that relevant for us at current stage of development, I'll briefly explain, because it might be important later.

   System usually has different categories. Those are `LC_CTYPE`, `LC_MESSAGES`, `LC_COLLATE`, `LC_MONETARY`, `LC_NUMERIC`, and `LC_TIME`. As you can see from their names, they govern locale specific information. For example, `LC_MONETARY` will contain formats for currency of current locale, `LC_TIME` — time format, and so on.

   There is also an `LC_ALL` category, which will call all other categories for current locale. It can be assumed as default.

   Those categories exists separately, because sometimes you want to switch locale to one, but category for another. For instance, to display messages in `pt`, but show dates in `en` format.

   For now, `node-gettext` can work only with one category — `LC_MESSAGES`. The one, which contain exactly translation of strings (messages). And generally whole idea doesn't apply that well to the web, since it easier to apply those formations by other libraries, like `moment` based on locale.

   But if we'd like to add categories support in future, we'd have some differences with GNU gettext in form of different signature.

   I'm not sure that we have to change new `setLocale`, to support category setting. It doesn't have much sense now, but might be important in future, if `node-gettext` will expand and decide to support formation of other entities. Some other libraries also might rely on current LC category.

# gettext.addTranslations(locale, domain, translations)

This is where things becoming especially different with GNU gettext.

1. GNU gettext doesn't have any methods like `addTranslation`, instead it has differently named `bindtextdomain()` method.

2. Signature of `bindtextdomain()` is different:

   ``` js
   gettext.addTranslations(locale, domain, translations)
   gettext.bindtextdomain(<domain>, <path to locales dir>)
   ```

   Notice that it doesn't ask nor about current locale, nor about path to file, from which should be loaded specified domain.

3. It took me a while to understand how that thing works.

   Turned out, that instead gettext `bindtextdomain` method accepts only PACKAGE (a name of domain), and LOCALEDIR (a path to files where all locales files stored, kinda cwd). And... that's all.

   As you can see, it doesn't ask about our current locale. It doesn't give us a way to specify `translations` object.

   Turned out, that it works very elegant. It doesn't ask about locale, because _it binds domain to our currently active locale_.

   In other words, if `node-gettext` wants follow GNU gettext, it should be not this

   ``` js
   gettext.addTranslations('en-US', 'myDomain', translations)
   ```

   but this

   ``` js
   gettext.setLocale('en-US')
   gettext.bindTextdomain('myDomain', '/locales/en')
   
   gettext.setLocale('to locale you\'d like to work with')
   ```

   And this will inject proper file as domain of current active locale.

   It also took me a while to understand, how GNU gettext figures out what to read and where to put everything, since it doesn't ask about path to specific file for bidden domain. Turns out, that GNU solves this quite elegantly too.

   Explanations can be read [here](https://www.gnu.org/software/gettext/manual/gettext.html#Ambiguities) and [here](https://www.gnu.org/software/gettext/manual/gettext.html#Locating-Catalogs).

   Here is illustration how gettext builds paths from entered parameters:

   ![sublime_text_2017-02-10_19-22-04](https://cloud.githubusercontent.com/assets/4460311/22838161/96a0c3f6-efcc-11e6-808c-0437d67a3aff.png)

   In this example
    
   ``` js
   `gettext.bindTextdomain('for/bar/nav', 'path/to/locales')`
   ```

   will result in `path/to/locales/en-US/LC_MESSAGE/for/bar/nav.{mo,po}` be available under

   ``` js
   `dgettext('for/bar/nav', 'Test message')`
   ```

   I especially liked how crazy simple solved issue with deeply nested domains — you just need to specify path as domain, and it will serve and as path for accessing this domain, and as path to domain file for gettext to read. Neat.

  You can check implementation of this behaviour in my pre-2.0.0 `node-gettext` version [here](https://github.com/LotusTM/Kotsu/blob/master/modules/gettext.coffee#L27).

  Few things:

   1) Yeap, it's relaying on set in `setLocale()` LC category. In my implementation it ignores it, and tries to access file both when there is `LC_MESSAGE` directory, and when there is no such. To be honest, can't say for now does it make sense to enforce structure of l10n catalog, as it does GNU gettext by making categories types mandatory, or no.
   2) Obliviously we don't want to make `bindTextdomain` read on it's own l10n files based on provided path. This will work great for Node, but not that needed in web, so we should replace second argument with something more relevant.

      For instance, it can accept or a function with injected domain as path (in case user wants to use his own loader and make it similar to GNU gettext), or a pure translation object with translations for currently active locale.

      This is something, that we should discuss in details, if we will decide to move closer to GNU gettext implementation. For now I've just gave some generic thoughts how that can be done.

# gettext.setTextDomain(domain)

Named as `textdomain(PACKAGE)` in GNU gettext. Can't say why it has `setlocale` with word `set`, but just a `textdomain` without `set` =\

In other terms seems to be similar to current `setTextDomain`, and in same way just switches domain in context of current active locale.

My only complain about it — I'd insist on `setTextdomain` name, since it's almost tradition to say `textdomain`, not `textDomain`.

You can look here: https://www.google.com.ua/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=%22textdomain%22. It will be quite difficult to find `textDomain` instead of `textdomain`.

On top of it, my subjective opinion — `setTextdomain` just looks much cleaner than `setTextDomain`.

# All together

I'd pay especial attention to how `bindTextdomain` works in GNU gettext.

It seems to have it logical work that way, especially considering discrepancy of `setTextDomain()`, which works only in context of current active locale, but `addTranslations` for some reason requires you to specify exact locale.

**Comment by alexanderwallin** [comment]
First of all, thanks for this thorough rundown!

I was about to answer it all point by point, but my takeaways are the following:

### Naming

The camel cased naming stays, with aliases for all methods that have a C equivalent. For instance: you can call both `setTextDomain(domain)` and `textdomain(domain)`. These aliases will be documented. This way you can skip the awkwardness of lowercase if you want, but still understand what it equals to; or use the traditional naming to keep consistent with gettext's original API.

### Categories

Like you said, I doubt anyone would turn here for dates, currencies or the similar when there are so many great libraries out there. I am happy to skip categories all-in-all and call `node-gettext` a gettext subset.

### `addTranslations(...)`, `bindtextdomain(...)` etc

`addTranslations(locale, domain, translations)` exists because there is no equivalent way of adding translations to gettext, since it is entirely file-based.

We can provide all the functionality that exists in the original gettext – like `bindtextdomain(domain_name, dir_name)` – but package it in a plugin inside `node-gettext`. We'll add a peer dependency on `gettext-parser`, since we'll be using this to parse .po and .mo files.

This can be released in 2.1.0.

**Comment by ArmorDarks** [comment]
Sorry for not replying for a while

I found some more information related to `setlocale` in Gettext, so I though it may be useful. At least, for those who will find this issue.

I was confused why in GUT Gettext `setlocale` accepts category (`LC_*`) as first argument, and locale as second. Since, well, it was logically to accept locale as first argument, since it's exactly what we want to change usually.

Turned out, that in GNU Gettext you do not set locales for Gettext. Instead, _you set locale for specified category_.

In other words

``` js
setlocale('LC_NUMERIC', 'pt-BR')
```

will set pt-BR locale for numeric values, not for all Gettext. Well, this is logically. This way you can control specific categories individually, by applying one locale for currency formatting, other for numbers, other for messages.

This `LC_*` is in fact nothing more than just a environmental OS variable, which you can retrieve and redefine with Gettext.

Here all categories:

```
LANG=C
LANGUAGE=
LC_CTYPE=fi_FI.UTF-8
LC_NUMERIC="C"
LC_TIME="C"
LC_COLLATE=fi_FI.UTF-8
LC_MONETARY="C"
LC_MESSAGES=fi_FI.UTF-8
LC_PAPER="C"
LC_NAME="C"
LC_ADDRESS="C"
LC_TELEPHONE="C"
LC_MEASUREMENT="C"
LC_IDENTIFICATION="C"
LC_ALL=
```

Some more information about this can be read [here](https://www.gnu.org/software/gettext/manual/html_node/Locale-Environment-Variables.html).

Well, that's all cool, but as we already mentioned few times, there is no sense in categories for node-gettext right now.

The only way as it could be used by know, is to expose those LC values, so that we could set locale, let's say, for numbers, with `LC_NUMERIC`, and then translate that category value to external library, like `numbro`. But it doesn't sound like justified approach. The only good thing in it is that we will introduce central provider for all categories — `node-gettext` categories.

However, I think we still should be prepared to some bright future, when categories might become part of `node-gettext`, and take into account all complications related to API changes.

So, here I think we have one good thing. We can leave `setLocale` to behave like it behaves right now — it will accept only one argument, locale.

If we ever introduce categories, we can say that `setLocale(locale)` is equal to `setlocale('LC_ALL', locale)` (which sets all categories to specified locale).

**Comment by ArmorDarks** [comment]
> The camel cased naming stays, with aliases for all methods that have a C equivalent. For instance: you can call both setTextDomain(domain) and textdomain(domain). These aliases will be documented. This way you can skip the awkwardness of lowercase if you want, but still understand what it equals to; or use the traditional naming to keep consistent with gettext's original API.

I agree, aliases should solve this issue.

> addTranslations(locale, domain, translations) exists because there is no equivalent way of adding translations to gettext, since it is entirely file-based.

> We can provide all the functionality that exists in the original gettext – like bindtextdomain(domain_name, dir_name) – but package it in a plugin inside node-gettext. We'll add a peer dependency on gettext-parser, since we'll be using this to parse .po and .mo files.

Yeap, I mentioned about this in my post. We can't use `bindtextdomain` in same way as it implemented in GNU Gettext, that's right.

However, I propose to make at least it closer to GNU one by doing following:

1. Replace`addTranslations` method with `bindTextDomain` and `bindtextdomain`
2. Change signature to `bindtextdomain(domainName, translationObject|loaderFunction)` (loaderFunction should return translation object)
3. It should not ask for locale name, Instead, it should work in contexts of previously setted locale with `setLocale(localeName)`
4. It should bind translation object under path `domainName` to current `localeName`
5. If as second argument used `loaderFunction`, `bindTextDomain` should execute it. As result it will expect prepared translation object, which will be placed under  `domainName`.

   To allow users construct proper paths to their l10n file in their loaders, `node-gettext` upon execution of function should inject two arguments:
   1. `localeName` — name of current locale
   2. `domainName` — name of current domain (which also serves as part of path, if domain have format of `foo/bar/nav`, in accordance with GNE gettext guidance).

   Those arguments will allow them to construct same to GNU Gettext paths: https://cloud.githubusercontent.com/assets/4460311/22838161/96a0c3f6-efcc-11e6-808c-0437d67a3aff.png

**Comment by ArmorDarks** [comment]
I also propose to add `textdomain` alias for `setTextDomain`, in accordance with GNU Gettext API.

**Comment by ArmorDarks** [comment]
And last thing — I really start to wonder why this lib called `node-gettext`, while we actually making more emphasis on browsers support by removing loader by default?

**Comment by alexanderwallin** [comment]
* Agreed on categories, let's possibly introduce that later!
* There will indeed be a `textdomain` alias
* I say let's provide `bindtextdomain` in the next release and create a separate issue for that!

The focus is on universal support, which means removing file reading from the core and moving it to optional plugins or extended cores. The only node-specific about v1 was to use `gettext-parser` if a file path was passed to the constructor. It is literally a one-liner that you can do yourself, and also an unnecessary dependency. There'll be some kind of recipe section to show examples of this in the README.

**Comment by ArmorDarks** [comment]
> I say let's provide bindtextdomain in the next release and create a separate issue for that!

Well, as you wish. To me it sounds slightly awkward to introduce _another_ way to add translations.

> The focus is on universal support, which means removing file reading from the core and moving it to optional plugins or extended cores.

Hm, I'm really not sure that this really means "universal support". What we're doing right now seems more like a browser-targeted approach.

I'm not against, since I do not see any difficulty in polyfilling expected for Node library functionality. But in same time it feels slightly strange, because usually when you add Node module you expect it to work completely out of box.

Probably, what we really have to do here is to serve different builds for different environments, like it does [Nunjucks](https://github.com/mozilla/nunjucks).

They serve to browser slimmed minified version, without Node-specific logic. Though, I never done anything like that, so can't tell how hard would be to do same thing.

Once again, personally I do not care much, but some people might be confused.

**Comment by alexanderwallin** [comment]
For updates of 2.0.0-rc.1 see:

* https://github.com/alexanderwallin/node-gettext/commit/8f522ae18eb9aa2f403b98f392c4f7569b318f01
* https://github.com/alexanderwallin/node-gettext/commit/139add7b1f24ae4598d4f1c91563f2654494be67
* https://github.com/alexanderwallin/node-gettext/commit/500626fd289f6c966db7c8b36c69f929bb77b93f
* https://github.com/alexanderwallin/node-gettext/commit/fb49a59bb9fe51ecb00c6250d5aa046338622750

**Comment by alexanderwallin** [comment]
> Well, as you wish. To me it sounds slightly awkward to introduce another way to add translations.

We have merely changed [this implicit parsing](https://github.com/alexanderwallin/node-gettext/blob/42e5ff598f217e1650466092733594be6091169c/lib/gettext.js#L29-L46) for the explicit [addTranslations(locale, domain, translations)](https://github.com/alexanderwallin/node-gettext/blob/42e5ff598f217e1650466092733594be6091169c/lib/gettext.js#L29-L46). The new way is neither less nor more compliant with gettext as far as I can tell.

> Hm, I'm really not sure that this really means "universal support". What we're doing right now seems more like a browser-targeted approach.

I don't see how? Previously you could pass a Buffer or String (that you had read yourself from the file system) to the constructor, and it would use `gettext-parser` to parse it for you. This you can easily do yourself.

We are planning to implement `bindtextdomain(...)`, which was not featured previously, so I would even claim we are being **more** server/GNU friendly than the last version. 😊
