### ISSUE TITLE
Should Gettext be a class?

### ISSUE THREAD

**Issue by ArmorDarks** [alexanderwallin/node-gettext#33]
This might sound as a stupid question, but, really, I'm not sure.

The more I code the less often I find any justifications for class usage for this or that methods.

For instance, currently Gettext is a class, and we should initiate it with `new` keyword.

However, does it really should be class? Do we have to pollute its prototype with methods? Does it give it any benefits? Will we extend `Gettext` instance anywhere?

Maybe I'm missing some point in using a class for Gettext?

**Comment by alexanderwallin** [comment]
It's designed using OOP, which I guess is what people are used to. It could just as well be functional.

Do you have any ideas on how to design it?

**Comment by ArmorDarks** [comment]
I do not have any particular ideas, but it's just something that bothers me. I think if something used, it should be used for a reason.

OOP doesn't mean that it should be a class. It could be just a singleton.

The main difference is that class\prototypes can be inherited, while singletons can't.

I just wonder, maybe I missing some additional point?

**Comment by jholster** [comment]
I agree with @ArmorDarks, Javascript is very well suited for writing OOP without classes,  constructors, prototypes, or _this_. But, while I personally prefer the said style ("this-less"), it's not mainstream, and structuring your code is mostly a matter of taste (of the project owner).

**Comment by ArmorDarks** [comment]
Yeap, I personally don't have anything nor against classes in general, nor against class-based approach in this lib. Just trying to understand the practical reasons for using it here.

So far I see two drawback in class-less approach:

1. If you need for some reason few instances of node-gettext, it will be harder to init fresh copies without `new`. But do we really need this with updated architecture?
2. You won't be able to extend  class. But I believe same thing still achievable through simple composition. Right?

**Comment by alexanderwallin** [comment]
Closing this.
