### ISSUE TITLE
Readme.md incorrectly uses readSync instead of readFileSync

### ISSUE THREAD

**Issue by marrobins** [alexanderwallin/node-gettext#37]
In the "Load and add translations from .mo or .po files" recipe, the code example uses the "readSync" method to load the contents of a file from a path. This is the wrong method - it should be "readFileSync".

"readSync" requires 5 input arguments - if you want to use readSync, the code would need to be changed:  https://nodejs.org/api/fs.html#fs_fs_readsync_fd_buffer_offset_length_position

**Comment by ArmorDarks** [comment]
That's right

@alexanderwallin Would you have time to fix it? Or should I make PR?

**Comment by alexanderwallin** [comment]
Cheers guys, I've updated it now.
