### ISSUE TITLE
How to handle placeholders?

### ISSUE THREAD

**Issue by SeanHayes** [alexanderwallin/node-gettext#38]
I have a string like:

    this.username + ' hasn’t uploaded any content!'

What's the recommended way of putting a placeholder inside the `gettext` string in JS?

**Comment by ArmorDarks** [comment]
Typically for this task used templating language.

It is common convention to use with Gettext `sprintf` (which can be found as JS port [here](https://github.com/alexei/sprintf.js)):

```js
sprintf(gettext('%(username)s has not uploaded any content!'), { username: this.username })
```

But you can use any suitable templating language. For instance, [Nunjucks](https://mozilla.github.io/nunjucks/) or [lodash.template](https://lodash.com/docs/4.17.4#template).

**Comment by joseluisq** [comment]
`sprintf` or `vsprintf` should solve strings with placeholders.

**Comment by SeanHayes** [comment]
Thanks!

**Comment by ArmorDarks** [comment]
> function translate (text, args = []) {
>  return args.length ? vsprintf(gt.gettext(text), args) : gt.gettext(text)
> }

Don't do that if you intend to extract translatable strings with automated tools like GNU's `xgettext`. They won't be able to recognize `translate` function. At least, without some additional configuration.
