### ISSUE TITLE
How to invoke msgen?

### ISSUE THREAD

**Issue by sabsaxo** [alexanderwallin/node-gettext#39]
I need to copy the msgid to msgstr, and see that this is a method of the gettext itself. Can I reach this somehow in node?

**Comment by ArmorDarks** [comment]
Whole instance object exposed to you, so after invocation, you can do with it whatever you want.

> and see that this is a method of the gettext itself

What exactly are you trying to do?

**Comment by alexanderwallin** [comment]
`node-gettext` doesn't really deal with creating .po or .pot files at the moment.
