### ISSUE TITLE
Unused code 

### ISSUE THREAD

**Issue by Xesenix** [alexanderwallin/node-gettext#44]
I have noticed there is some  `event listener` functionality that isn't used. I would expect some event triggered on locale change or not wasting size.

Also `this.setLomain` doesn't exist anywhere:
https://github.com/alexanderwallin/node-gettext/blob/a9c955c1ea2069b487927ca9c9d46a1981641a12/lib/gettext.js#L395

**Comment by alexanderwallin** [comment]
The listeners are currently for errors!
