### ISSUE TITLE
Any clever way of checking if a translation is already added?

### ISSUE THREAD

**Issue by sabsaxo** [alexanderwallin/node-gettext#45]
To avoid contacting the server over and over again (even though cached).

**Comment by ArmorDarks** [comment]
After you've done `let gt = new Gettext(...)`, you can check internals of the `gt`. Translations object completely exposed to you, so you can do any check you'd like to.

**Comment by sabsaxo** [comment]
Yeah, figured I had to manually do that. Thanks.
