### ISSUE TITLE
Add getLocale

### ISSUE THREAD

**Issue by pronebird** [alexanderwallin/node-gettext#48]
Hi,

Could you please add a `getLocale()` method. I am trying to suppress the "No translation was found" errors for the source language but I have no access to the locale and it's cumbersome to add more state around my code because I load things asynchronously.

Cheers,
Andrej

**Comment by pronebird** [comment]
Missing `getTextDomain()` for default domain too.

**Comment by alexanderwallin** [comment]
Late response, but you can now define a `sourceLocale`!

**Comment by alexanderwallin** [comment]
And just between you and me, there are `.locale` and `.domain` attributes on you GetText instance. :)

**Comment by pronebird** [comment]
@alexanderwallin thanks for the v3.0 release! I guess since I use TypeScript, it's more of a typings issue, I still have to cheat TypeScript typings to access the `.domain`. Maybe I'll submit a patch to typings
```ts
  // NOTE: domain is not publicly exposed
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const domain = (catalogue as any).domain;
```

**Comment by alexanderwallin** [comment]
This is great, thank you!
