### ISSUE TITLE
Unexpected identifier / Gettext is not a constructor using Node v10.15.3

### ISSUE THREAD

**Issue by d3v-one** [alexanderwallin/node-gettext#51]
Hi.

trying to use a minimal code example
```
import Gettext from 'node-gettext'
const gt = new Gettext();
```
results in the following error message:

`SyntaxError: Unexpected identifier`

The minimal code example
```
const { Gettext } = require('node-gettext');
const gt = new Gettext();
```
results in the following error message:

`TypeError: Gettext is not a constructor`

The latter can be remedied by changing line 6 in the file lib/gettext.js  from

`module.exports = Gettext;`

to

`module.exports.Gettext = Gettext;`

Is this triggered by new Node.js versions or am I missing something here?

Regards,
Mike

**Comment by snmhinge** [comment]
try to get it using const Gettext = require('node-gettext/lib/gettext');

**Comment by resynth1943** [comment]
1. The `import` operator isn't *yet* implemented in Node, which is why you're getting the SyntaxError.
2. Instead of destructuring, try `require('node-gettext')`. The default export is returned.

I think you're missing something here. If my solutions do work, consider closing this issue.

**Comment by d3v-one** [comment]
The working solution, suggested by @snmhinge, is:
```
const Gettext = require('node-gettext/lib/gettext');
const gt = new Gettext();
```
